create table categorias (
    id bigint generated by default as identity,
    descricao varchar(100) not null,
    primary key (id)
);


create table notas (
        id bigint generated by default as identity,
        id_categoria bigint,
        conteudo varchar(500) not null,
        primary key (id)
    );

alter table if exists notas 
    add constraint FKfkmr0xr5ecccjy00co7db8709 
    foreign key (id_categoria) 
    references categorias;


-- insert into categorias (descricao)
-- values ('Java'),
--     ('Dart'),
--     ('Kotlin'),
--     ('C++'),
--     ('Python');